[package]
name = "code-brute-forcer"
version = "0.1.0"
edition = "2021"
authors = ["frankcai <frankcai@gmx.de>"]
description = "Tool to brute force possible codes from a given code where some characters are missing"
license = "MIT"

[dependencies]
regex = "1"